name: expense_tracker
description: A modern expense tracker app with Node.js backend
publish_to: 'none'
version: 1.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  intl: ^0.19.0
  fl_chart: ^0.65.0
  animations: ^2.0.11
  package_info_plus: ^4.0.0
  ota_update: ^7.0.2
  # Icons
  flutter_svg: ^2.0.9
  
  # Date Picker
  flutter_datetime_picker_plus: ^2.1.0
  open_file: ^3.5.10
  permission_handler: ^12.0.1
    
  # Image Picker
  image_picker: ^1.0.7
  
  introduction_screen: ^4.0.0
  local_auth: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
